require: rubocop-rails

AllCops:
  Exclude:
    - node_modules/**/*
    - db/schema.rb

Rails/ApplicationController:
  Exclude:
    - spec/**/*.rb

Rails/OutputSafety:
  Exclude:
    - spec/**/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - db/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - db/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/**/*.rb

Style/MixinUsage:
  Exclude:
    - bin/*

Style/FrozenStringLiteralComment:
  Exclude:
    - bin/*

Naming/MemoizedInstanceVariableName:
  Description: >-
    Memoized method name should match memo instance variable name.
  Enabled: true
  EnforcedStyleForLeadingUnderscores: required

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Rails/FilePath:
  Enabled: false
