/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of DestroyBar
 */
export interface DestroyBarInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateBar
 */
export interface UpdateBarInput {
  id: string;
  title?: string | null;
  content?: string | null;
  isActive?: boolean | null;
  isSticky?: boolean | null;
  isFullWidthLink?: boolean | null;
  isNewTabUrl?: boolean | null;
  hasCloseButton?: boolean | null;
  url?: string | null;
  placement?: string | null;
  themeTemplates?: string[] | null;
  paddingY?: string | null;
  paddingX?: string | null;
  textAlign?: string | null;
  textColor?: string | null;
  fontSize?: string | null;
  backgroundColor?: string | null;
  clientMutationId?: string | null;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
